name: Smart Contracts CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [8.x, 10.x, 12.x, 14.x]
        node-version: [14.x]

    env:
      NODE_ENV: develop
      DSLA_INFURA_PROJECT_ID: ba374d41ee3f4c65ab05c31c4dd452f6
      TEST_MNEMONIC: myth like bonus scare over problem client lizard pioneer submit female collect
      DSLA_MNEMONIC: rich trumpet output release matter miss total order focus mimic section weapon
      STAGING_IP: 134.209.42.213

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm install
      - run: npm install truffle
      - run: ./node_modules/truffle/build/cli.bundled.js test --network staging
